# Generated by Django 5.0.1 on 2024-01-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=120)),
                ('messege', models.CharField(max_length=200)),
            ],
        ),
    ]
